name: Rush CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: rush install
      run: |
        echo 'Installing...'
        node common/scripts/install-run-rush.js install
    - name: rush check
        echo 'Installing...'
        node common/scripts/install-run-rush.js check
    - name: rush test
        echo 'Testing...'
        node common/scripts/install-run-rush.js test --verbose
    - name: rush lint
        echo 'Linting...'
        node common/scripts/install-run-rush.js lint --verbose
    - name: rush build
        echo 'Building...'
        node common/scripts/install-run-rush.js rebuild
      env:
        CI: true
        NODE_ENV: production
